import {STATUSES,uid,today,addDays,dayRange,daysBetween,summary,validateTask,deriveProgress,validateProject,normalizeEmails,safeUrl,demoData} from './model.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SPAN=60;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let demo=new URLSearchParams(location.search).has('demo'),user=null,store=null,projects=[],tasks=[],selectedId=null,unsubscribeTasks=()=>{},editing=null,editingProject=null,draftChecks=[],view='timeline',month=today(),toastTimer,loading=false,shareVersion=null;
const demoTasks=new Map();
let pendingProjectId=null;
const canEdit=()=>demo||!!user?.canEdit;
const current=()=>projects.find(p=>p.id===selectedId);
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
function connection(text,live=false){$('#connection').textContent=text;$('#connection').classList.toggle('live',live);}
function errorMessage(error){if(error.code==='unavailable')return '연결이 끊어졌습니다. 입력 내용을 유지했으니 연결 후 다시 저장해주세요.';if(error.code?.startsWith('auth/'))return error.code==='auth/too-many-requests'?'로그인 시도가 많습니다. 잠시 후 다시 시도해주세요.':'로그인에 실패했습니다. 이메일과 비밀번호, 네트워크 연결을 확인해주세요.';return error.message||'작업을 처리하지 못했습니다. 다시 시도해주세요.';}
async function busy(form,work){const controls=[...form.querySelectorAll('button')];controls.forEach(b=>b.disabled=true);try{await work();}finally{controls.forEach(b=>b.disabled=false);}}
const hasName=()=>demo||!!user?.named;let afterName=null;function askName(then=null){afterName=then;const f=$('#github-form');f.elements.name.value=user?.named?user.email:'';$('#github-error').textContent='';$('#github-dialog').showModal();}
function displayAccount(){const name=demo?'샘플 체험':user?.named?user.email:'이름 미설정';$('#account-name').textContent=name;$('#avatar').textContent=name.slice(0,1).toUpperCase();$('#demo-banner').hidden=!demo;$('#workspace').hidden=false;$('#connect-github').hidden=demo;$('#connect-github').textContent=hasName()?'이름 변경':'내 이름 설정';$('#refresh').hidden=demo;}

function switchProject(id){if(selectedId===id)return;if(demo&&selectedId)demoTasks.set(selectedId,tasks);selectedId=id;tasks=demo?(demoTasks.get(id)||[]):[];unsubscribeTasks();const p=current();if(p){const t=today();month=p.start;if(!demo){loading=true;unsubscribeTasks=store.watchTasks(id,(rows,cached)=>{tasks=rows;loading=false;connection(cached?'연결 확인 중':'공유 데이터 연결됨',!cached);render();if(editing&&$('#task-dialog').open){const latest=tasks.find(t=>t.id===editing.id);$('#conflict-note').hidden=!!latest&&latest.version===editing.version;}},e=>{loading=false;tasks=[];connection('공유 데이터 확인 필요');render();$('#board-content').innerHTML=`<div class="empty-result">${esc(errorMessage(e))}</div>`;});}}const url=new URL(location.href);if(id)url.searchParams.set('project',id);else url.searchParams.delete('project');history.replaceState(null,'',url);render();}
function render(){const p=current();$('#project-list').innerHTML=projects.map(p=>`<button class="project-nav ${p.id===selectedId?'active':''}" data-project="${esc(p.id)}">${esc(p.name)}</button>`).join('');$('#empty-projects').hidden=!!p;$('.project-heading').hidden=!p;$('.board').hidden=!p;$('#attention').hidden=!p;if(!p)return;$('#project-title').textContent=p.name;$('#project-desc').textContent=p.description;$('#project-period').textContent=`${p.start.replaceAll('-','.')} — ${p.end.replaceAll('-','.')}`;$('#member-count').textContent='링크로 함께 관리';$('#project-settings').disabled=!canEdit();$('#new-task').disabled=!canEdit();const sum=summary(tasks);$('#stat-percent').innerHTML=`${sum.percent}<em>%</em>`;$('#overall-progress').style.width=sum.percent+'%';$('#stat-done-text').textContent=`업무 ${sum.total}개 중 ${sum.done}개 완료${sum.late?` · 지연 ${sum.late}`:''}`;$('#mobile-project').innerHTML=projects.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');$('#mobile-project').value=p.id;const prev=$('#owner-filter').value;const owners=[...new Set(tasks.map(t=>t.owner).filter(Boolean))].sort();$('#owner-filter').innerHTML='<option value="all">모든 담당자</option><option value="unassigned">미지정</option>'+owners.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('');$('#owner-filter').value=[...$('#owner-filter').options].some(o=>o.value===prev)?prev:'all';$('#owners').innerHTML=owners.map(o=>`<option>${esc(o)}</option>`).join('');renderBoard();$('#attention').innerHTML=(sum.blocked?`<button class="attention-item" data-attention="blocked"><span>⚑</span><span><b>도움이 필요한 업무 ${sum.blocked}건</b> · 막힌 이유를 확인하고 함께 해결해주세요.</span></button>`:'')+(sum.unassigned?`<button class="attention-item" data-attention="unassigned"><span>◎</span><span><b>담당자 미지정 ${sum.unassigned}건</b> · 업무를 맡을 사람을 정해주세요.</span></button>`:'');}
function filtered(){const search=$('#search').value.toLowerCase(),status=$('#status-filter').value,owner=$('#owner-filter').value;return tasks.filter(t=>(t.title+' '+t.phase+' '+t.owner).toLowerCase().includes(search)&&(status==='all'||(status==='late'?t.end<today()&&t.status!=='done':t.status===status))&&(owner==='all'||(owner==='unassigned'?!t.owner:t.owner===owner))).sort((a,b)=>a.start.localeCompare(b.start)||a.title.localeCompare(b.title));}
function renderBoard(){const rows=filtered(),p=current();if(!p)return;$('#month-label').textContent=`${month.replaceAll('-','.')} ~ ${addDays(month,SPAN-1).slice(5).replace('-','.')}`;$('#task-count').textContent=`업무 ${rows.length}개 / 전체 ${tasks.length}개`;
if(loading){$('#board-content').innerHTML='<div class="empty-result">업무를 불러오고 있습니다…</div>';return;}if(!rows.length){$('#board-content').innerHTML=`<div class="empty-result">${tasks.length?'조건에 맞는 업무가 없습니다. 필터를 변경해보세요.':'아직 등록된 업무가 없습니다. 첫 업무를 추가해보세요.'}<br><button class="btn primary" style="margin-top:16px" data-new-task>＋ 업무 추가</button></div>`;return;}
if(view==='list'){$('#board-content').innerHTML=`<table class="list-table"><thead><tr><th>업무</th><th>담당자</th><th>상태</th><th>일정</th><th>진행률</th><th>하위 업무</th></tr></thead><tbody>${rows.map(t=>`<tr data-task="${esc(t.id)}"><td><button class="btn ghost" data-task="${esc(t.id)}">${esc(t.title)}</button></td><td>${esc(t.owner||'미지정')}</td><td><span class="badge ${esc(t.status)}">${STATUSES[t.status]}</span></td><td class="${t.end<today()&&t.status!=='done'?'late-text':''}">${t.start.slice(5)} ~ ${t.end.slice(5)}</td><td>${t.percent}%</td><td>${t.checklist.filter(c=>c.done).length}/${t.checklist.length}</td></tr>`).join('')}</tbody></table>`;return;}
const first=month,last=addDays(first,SPAN-1),days=dayRange(first,last),week=['일','월','화','수','목','금','토'];
$('#month-label').textContent=`${first.replaceAll('-','.')} ~ ${last.slice(5).replace('-','.')}`;
const dayClass=d=>`${[0,6].includes(new Date(d).getUTCDay())?'weekend':''} ${d===today()?'today':''} ${d.endsWith('-01')?'month-start':''}`;
let html=`<div class="timeline"><div class="timeline-row date-header"><div class="row-label"><span>업무 / 하위 업무</span><span>담당자</span></div><div class="days">${days.map((d,k)=>`<div class="day-cell ${dayClass(d)}" data-date="${d}"><span class="${k===0||d.endsWith('-01')?'mon':''}">${k===0||d.endsWith('-01')?Number(d.slice(5,7))+'월':week[new Date(d).getUTCDay()]}</span><b>${Number(d.slice(-2))}</b></div>`).join('')}</div></div>`;
const pos=(a,b)=>posStyle(first,a,b);
const phases=[...new Set(rows.map(t=>t.phase||'일반'))];for(const phase of phases){const group=rows.filter(t=>(t.phase||'일반')===phase);html+=`<div class="timeline-row group-row"><div class="row-label">${esc(phase)} <span class="group-count">${group.length}</span></div><div class="group-fill"></div></div>`;for(const t of group){const begin=t.start<first?first:t.start,finish=t.end>last?last:t.end,visible=begin<=last&&finish>=first;const label=`${t.title} · ${STATUSES[t.status]} · ${t.percent}%`;const late=t.end<today()&&t.status!=='done';const hasSubs=t.checklist.length>0;
html+=`<div class="timeline-row task-row ${esc(t.status)} ${hasSubs?'has-subs':''}"><button class="row-label" data-task="${esc(t.id)}"><span class="status-icon ${esc(t.status)}">${t.status==='done'?'✓':t.status==='blocked'?'!':''}</span><span class="task-text"><span class="task-name">${esc(t.title)}</span><span class="task-sub"><span class="task-pct">${t.percent}%</span><span>하위 ${t.checklist.filter(c=>c.done).length}/${t.checklist.length}</span><span class="${late?'late-text':''}">${late?'지연 · ':''}${STATUSES[t.status]}</span></span></span><span class="owner-pill ${!t.owner?'unassigned':''}">${esc(t.owner||'미지정')}</span></button><div class="days">${days.map(d=>`<button class="day-cell ${dayClass(d)} ${t.logs.some(l=>l.date===d)?'has-log':''}" data-task="${esc(t.id)}" data-log-date="${d}" aria-label="${esc(t.title)} ${d} 추진 기록"></button>`).join('')}${visible?`<button class="bar ${esc(t.status)}" style="${pos(begin,finish)}" data-task="${esc(t.id)}" title="${esc(label)}" aria-label="${esc(label)}"><i class="bar-fill" style="width:${t.percent}%"></i><span>${esc(t.title)}</span><b>${t.percent}%</b></button>`:''}${visible&&hasSubs?`<i class="trunk-start" style="left:calc(${daysBetween(first,begin)} * var(--day) + 10px)"></i>`:''}</div></div>`;
html+=subRows(t,first,last,days,dayClass,visible?begin:null);}}$('#board-content').innerHTML=html+'</div>';fitDays();}
function posStyle(first,a,b){return `left:calc(${daysBetween(first,a)} * var(--day) + 2px);width:calc(${daysBetween(a,b)+1} * var(--day) - 4px)`;}
function fitDays(){const tl=$('.timeline');if(!tl)return;const label=parseFloat(getComputedStyle(tl).getPropertyValue('--label'))||280;const w=$('#board-content').clientWidth-label-2;tl.style.setProperty('--day',Math.max(18,Math.floor(w/SPAN))+'px');}
function subRows(t,first,last,days,dayClass,parentBegin){const n=t.checklist.length;return t.checklist.map((c,k)=>{const s=c.start||t.start,e=c.end||t.end,b=s<first?first:s,f=e>last?last:e,vis=b<=last&&f>=first,late=!c.done&&e<today(),cls=c.done?'done':late?'late':'',isLast=k===n-1,key=`${t.id}|${c.id}`;const notes=c.notes||[];
const mark=c.done&&c.doneAt&&c.doneAt>=first&&c.doneAt<=last?`<span class="done-mark" style="left:calc(${daysBetween(first,c.doneAt)} * var(--day) + var(--day) / 2 - 8px)" title="${esc(c.doneAt)} 완료">✓</span>`:'';
const link=parentBegin&&vis?`<i class="sub-link ${isLast?'last':''}" style="left:calc(${daysBetween(first,parentBegin)} * var(--day) + 10px);width:max(4px, calc(${daysBetween(parentBegin,b)} * var(--day) - 8px))"></i>${isLast?'':`<i class="sub-trunk" style="left:calc(${daysBetween(first,parentBegin)} * var(--day) + 10px)"></i>`}`:'';
const label=`${c.text} · ${s.slice(5)}~${e.slice(5)}${c.done?' · '+(c.doneAt||'').slice(5)+' 완료':late?' · 지연':''}${notes.length?` · 기록 ${notes.length}건`:''}`;
return `<div class="timeline-row sub-row ${isLast?'last':''}"><div class="row-label"><i class="tree"></i><button type="button" class="sub-toggle ${cls}" data-toggle-sub="${esc(key)}" aria-label="${esc(c.text)} ${c.done?'완료 취소':'완료 처리'}" title="${c.done?'완료 취소':'완료 체크'}">${c.done?'✓':''}</button><button type="button" class="sub-open" data-sub="${esc(key)}" title="${esc(label)}"><span class="sub-name ${c.done?'is-done':''}">${esc(c.text)}</span>${notes.length?`<span class="sub-notes">✎${notes.length}</span>`:''}${late?'<span class="late-text sub-late">지연</span>':''}</button></div><div class="days">${days.map(d=>`<button type="button" class="day-cell ${dayClass(d)} ${notes.some(x=>x.date===d)?'has-log':''}" data-sub="${esc(key)}" data-log-date="${d}" aria-label="${esc(c.text)} ${d} 기록"></button>`).join('')}${link}${vis?`<button type="button" class="sub-bar ${cls}" style="${posStyle(first,b,f)}" data-sub="${esc(key)}" title="${esc(label)}" aria-label="${esc(label)}"><span>${esc(c.text)}</span></button>`:''}${mark}</div></div>`;}).join('');}
async function persistTask(record){if(demo){const at=tasks.findIndex(t=>t.id===record.id);record.version++;if(at<0)tasks.push(record);else tasks[at]=record;render();}else await store.saveTask(selectedId,record);}
async function toggleSub(tid,cid){if(!canEdit())return;if(!hasName()){askName(()=>toggleSub(tid,cid));return;}const t=tasks.find(x=>x.id===tid);if(!t)return;const rec=structuredClone(t);const c=rec.checklist.find(x=>x.id===cid);if(!c)return;c.done=!c.done;c.doneAt=c.done?today():'';try{let r=validateTask(rec);r.logs.push({id:uid(),date:today(),note:`하위 업무 ${c.done?'완료':'완료 취소'}: ${c.text}`,status:r.status,percent:r.percent,author:user.email,createdAt:new Date().toISOString()});r=validateTask(r);const at=tasks.findIndex(x=>x.id===tid);if(!demo){tasks[at]={...r};render();}await persistTask(r);toast(c.done?`'${c.text}' 완료 (${r.percent}%)`:`'${c.text}' 완료를 취소했습니다.`);}catch(err){tasks[tasks.findIndex(x=>x.id===tid)]=t;render();toast(errorMessage(err));}}
let editingSub=null;
function openSub(tid,cid,date=today()){const t=tasks.find(x=>x.id===tid),c=t?.checklist.find(x=>x.id===cid);if(!c)return;editingSub={tid,cid,version:t.version};const f=$('#sub-form');f.reset();$('#sub-parent').textContent=t.title;f.elements.text.value=c.text;f.elements.start.value=c.start||t.start;f.elements.end.value=c.end||t.end;f.elements.start.min=f.elements.end.min=t.start;f.elements.start.max=f.elements.end.max=t.end;f.elements.done.checked=!!c.done;$('#sub-done-at').textContent=c.done&&c.doneAt?`${c.doneAt.replaceAll('-','.')} 완료`:'';f.elements.noteDate.value=date;$('#sub-error').textContent='';const notes=[...(c.notes||[])].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));$('#sub-history').innerHTML=notes.map(n=>`<article class="history-entry"><div class="history-meta"><b>${esc(n.date)}</b><span>${esc(n.author)}</span></div><p>${esc(n.note)}</p></article>`).join('')||'<p class="helper">아직 기록이 없습니다.</p>';$('#sub-dialog').showModal();f.elements.note.focus();}
$('#sub-form').onsubmit=async e=>{e.preventDefault();if(!hasName()){askName();return;}const f=e.target;$('#sub-error').textContent='';await busy(f,async()=>{try{const t=tasks.find(x=>x.id===editingSub.tid);if(!t)throw Error('다른 사람이 이 업무를 삭제했습니다.');if(t.version!==editingSub.version)throw Error('다른 사람이 이 업무를 먼저 수정했습니다. 입력한 기록을 복사해 두고 다시 열어주세요.');const rec=structuredClone(t),c=rec.checklist.find(x=>x.id===editingSub.cid);if(!c)throw Error('이 하위 업무가 삭제되었습니다.');const wasDone=c.done;c.text=f.elements.text.value.trim();c.start=f.elements.start.value;c.end=f.elements.end.value;c.done=f.elements.done.checked;if(c.done&&!wasDone)c.doneAt=today();if(!c.done)c.doneAt='';const note=f.elements.note.value.trim();c.notes=c.notes||[];if(note)c.notes.push({id:uid(),date:f.elements.noteDate.value,note,author:user.email,createdAt:new Date().toISOString()});let r=validateTask(rec);if(c.done!==wasDone)r.logs.push({id:uid(),date:today(),note:`하위 업무 ${c.done?'완료':'완료 취소'}: ${c.text}`,status:r.status,percent:r.percent,author:user.email,createdAt:new Date().toISOString()});r=validateTask(r);await persistTask(r);$('#sub-dialog').close();toast('하위 업무를 저장했습니다.');}catch(err){$('#sub-error').textContent=errorMessage(err);}});};
window.addEventListener('resize',()=>fitDays());
function newTask(date=today()){if(!canEdit())return;if(!hasName()){askName(()=>newTask(date));return;}const p=current();if(!p)return;openTask({id:null,title:'',phase:'준비',owner:'',start:date<p.start?p.start:date>p.end?p.end:date,end:date<p.start?p.start:date>p.end?p.end:date,status:'todo',percent:0,blocker:'',link:'',checklist:[],logs:[],version:0},date);}
function openTask(task,date=today()){editing=structuredClone(task);draftChecks=structuredClone(task.checklist).map(c=>({...c,start:c.start||task.start,end:c.end||task.end}));const form=$('#task-form');form.reset();for(const key of ['title','phase','owner','start','end','status','blocker','link'])form.elements.namedItem(key).value=task[key]??'';form.elements.logDate.value=date;$('#task-mode').textContent=task.id?'업무 상세':'새로운 업무';$('#task-dialog-title').textContent=task.id?'업무 수정':'업무 추가';$('#task-error').textContent='';$('#conflict-note').hidden=true;$('#delete-task').hidden=!task.id;renderChecks();renderStatus();$('#task-history').innerHTML=[...task.logs].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)).map(l=>`<article class="history-entry"><div class="history-meta"><b>${esc(l.date)}</b><span>${esc(l.author)}</span></div><p>${esc(l.note)}</p><div class="history-state">${STATUSES[l.status]} · ${l.percent}%</div></article>`).join('')||'<p class="helper">아직 등록된 추진 기록이 없습니다.</p>';for(const field of form.querySelectorAll('input,textarea,select,button:not([data-close])'))field.disabled=!canEdit();form.querySelector('[type=submit]').hidden=!canEdit();$('#delete-task').hidden=!canEdit()||!task.id;if(canEdit())renderStatus();$('#task-dialog-title').textContent=canEdit()?(task.id?'업무 수정':'업무 추가'):'업무 상세';$('#task-dialog').showModal();$('#task-form .dialog-body').scrollTop=0;}
function renderChecks(){const ro=!canEdit();$('#checklist').innerHTML=draftChecks.map(c=>`<div class="check-row"><label><input type="checkbox" data-check="${esc(c.id)}" ${c.done?'checked':''} ${ro?'disabled':''}><span class="check-text"><span class="check-name">${esc(c.text)}</span>${c.done&&c.doneAt?`<small class="done-at">${esc(c.doneAt.slice(5).replace('-','/'))} 완료</small>`:''}</span></label><span class="check-dates"><input type="date" data-check-start="${esc(c.id)}" value="${esc(c.start||'')}" aria-label="${esc(c.text)} 시작일" ${ro?'disabled':''}><span>~</span><input type="date" data-check-end="${esc(c.id)}" value="${esc(c.end||'')}" aria-label="${esc(c.text)} 마감일" ${ro?'disabled':''}></span>${ro?'':`<button type="button" class="icon-btn" data-remove-check="${esc(c.id)}" aria-label="${esc(c.text)} 삭제">×</button>`}</div>`).join('')||'<p class="helper">하위 업무를 추가하면 완료 개수에 따라 진행률이 자동으로 채워집니다.</p>';syncProgress();}
function syncProgress(){const f=$('#task-form'),pr=deriveProgress(draftChecks,f.elements.status.value);$('#check-count').textContent=`${pr.done} / ${pr.total}`;if(pr.total)f.elements.status.value=pr.status;f.elements.status.querySelector('option[value=done]').disabled=pr.total>0&&pr.done<pr.total;$('#percent-label').textContent=pr.percent+'%';$('#task-progress').style.width=pr.percent+'%';$('#progress-hint').textContent=pr.total?`하위 업무 ${pr.total}개 중 ${pr.done}개 완료`:'하위 업무가 없으면 상태가 완료일 때 100%가 됩니다.';$('#blocker-label').hidden=f.elements.status.value!=='blocked';f.elements.blocker.required=f.elements.status.value==='blocked';}
function renderStatus(){syncProgress();}
function clampChecks(){const f=$('#task-form'),a=f.elements.start.value,b=f.elements.end.value;if(!a||!b||a>b)return;for(const c of draftChecks){if(!c.start||c.start<a)c.start=a;if(c.start>b)c.start=b;if(!c.end||c.end>b)c.end=b;if(c.end<a)c.end=a;if(c.end<c.start)c.end=c.start;}renderChecks();}
function openProject(existing=false){if(!canEdit())return;if(!hasName()){askName(()=>openProject(existing));return;}editingProject=existing?structuredClone(current()):null;const f=$('#project-form');f.reset();f.elements.name.value=editingProject?.name??'';f.elements.description.value=editingProject?.description??'';f.elements.start.value=editingProject?.start??today();f.elements.end.value=editingProject?.end??addDays(today(),30);$('#project-dialog-title').textContent=existing?'프로젝트 설정':'새 프로젝트';$('#project-error').textContent='';$('#project-dialog').showModal();}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){close.closest('dialog').close();return;}const project=e.target.closest('[data-project]');if(project){switchProject(project.dataset.project);return;}const tog=e.target.closest('[data-toggle-sub]');if(tog){const [tid,cid]=tog.dataset.toggleSub.split('|');toggleSub(tid,cid);return;}const subEl=e.target.closest('[data-sub]');if(subEl){const [tid,cid]=subEl.dataset.sub.split('|');openSub(tid,cid,subEl.dataset.logDate||today());return;}const task=e.target.closest('[data-task]');if(task){const record=tasks.find(t=>t.id===task.dataset.task);if(record)openTask(record,task.dataset.logDate||today());return;}if(e.target.closest('[data-new-task]'))newTask();const del=e.target.closest('[data-remove-check]');if(del){draftChecks=draftChecks.filter(c=>c.id!==del.dataset.removeCheck);renderChecks();}const metric=e.target.closest('[data-metric],[data-attention]');if(metric){const value=metric.dataset.metric||metric.dataset.attention;$('#status-filter').value=['done','late','blocked'].includes(value)?value:'all';$('#owner-filter').value=value==='unassigned'?'unassigned':'all';renderBoard();}});
$('#checklist').addEventListener('change',e=>{const d=e.target.dataset;const c=draftChecks.find(c=>c.id===(d.check||d.checkStart||d.checkEnd));if(!c)return;if(d.check){c.done=e.target.checked;c.doneAt=c.done?($('#task-form').elements.logDate.value||today()):'';}else if(d.checkStart){c.start=e.target.value;if(c.end<c.start)c.end=c.start;}else{c.end=e.target.value;if(c.start>c.end)c.start=c.end;}renderChecks();});
$('#task-form').elements.start.addEventListener('change',clampChecks);$('#task-form').elements.end.addEventListener('change',clampChecks);
$('#add-check').onclick=()=>{const input=$('#check-input'),text=input.value.trim();if(!text)return;if(draftChecks.length>=50){toast('하위 업무는 최대 50개까지 등록할 수 있습니다.');return;}const tf=$('#task-form');draftChecks.push({id:uid(),text,done:false,start:tf.elements.start.value,end:tf.elements.end.value,doneAt:''});input.value='';renderChecks();input.focus();};$('#check-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#add-check').click();}};
$('#task-form').elements.status.onchange=renderStatus;
$('#task-form').onsubmit=async e=>{e.preventDefault();if(!hasName()){askName();return;}const form=e.target;$('#task-error').textContent='';await busy(form,async()=>{try{const data=Object.fromEntries(new FormData(form)),p=current();let record=validateTask({...editing,...data,percent:0,checklist:draftChecks,logs:[...editing.logs]});if(record.start<p.start||record.end>p.end)throw Error('업무 일정은 프로젝트 시작일과 종료일 안에 설정해주세요.');const before=new Map((editing.checklist||[]).map(c=>[c.id,c.done]));const subLogs=record.checklist.filter(c=>c.done&&!before.get(c.id)).map(c=>({id:uid(),date:c.doneAt,note:`하위 업무 완료: ${c.text}`,status:record.status,percent:record.percent,author:user.email,createdAt:new Date().toISOString()}));record.logs.push(...subLogs);if(data.note.trim()){record.logs.push({id:uid(),date:data.logDate,note:data.note.trim(),status:record.status,percent:record.percent,author:user.email,createdAt:new Date().toISOString()});}else if(editing.id&&!subLogs.length&&(editing.status!==record.status||editing.percent!==record.percent)){record.logs.push({id:uid(),date:today(),note:`상태 변경: ${STATUSES[record.status]} (${record.percent}%)`,status:record.status,percent:record.percent,author:user.email,createdAt:new Date().toISOString()});}delete record.note;delete record.logDate;record=validateTask(record);if(demo){record.id=record.id||uid();record.version++;const at=tasks.findIndex(t=>t.id===record.id);if(at<0)tasks.push(record);else tasks[at]=record;render();}else await store.saveTask(selectedId,record);$('#task-dialog').close();toast(demo?'샘플에 반영했습니다.':'변경사항을 저장했습니다.');}catch(err){$('#task-error').textContent=errorMessage(err);}});};
$('#delete-task').onclick=()=>$('#confirm-dialog').showModal();$('#confirm-dialog').addEventListener('close',async()=>{if($('#confirm-dialog').returnValue!=='delete')return;await busy($('#task-form'),async()=>{try{if(demo){tasks=tasks.filter(t=>t.id!==editing.id);render();}else await store.deleteTask(selectedId,editing);$('#task-dialog').close();toast('업무를 삭제했습니다.');}catch(e){$('#task-error').textContent=errorMessage(e);}});});
$('#project-form').onsubmit=async e=>{e.preventDefault();const f=e.target;$('#project-error').textContent='';await busy(f,async()=>{try{const data=validateProject({...editingProject,...Object.fromEntries(new FormData(f))});if(editingProject&&tasks.some(t=>t.start<data.start||t.end>data.end))throw Error('기존 업무가 새 프로젝트 기간을 벗어납니다. 업무 일정을 먼저 조정해주세요.');if(demo){if(editingProject){Object.assign(current(),data,{version:current().version+1});render();}else{data.id=uid();Object.assign(data,{ownerUid:user.uid,ownerEmail:user.email,memberEmails:[user.email],version:1});projects.push(data);switchProject(data.id);}}else{const id=await store.saveProject(data);if(!editingProject){pendingProjectId=id;if(projects.some(p=>p.id===id)){switchProject(id);pendingProjectId=null;}toast('프로젝트를 만들었습니다.');}}$('#project-dialog').close();}catch(err){$('#project-error').textContent=errorMessage(err);}});};
$('#share').onclick=()=>{$('#share-url').value=location.href;$('#share-dialog').showModal();};
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('#share-url').value);toast('프로젝트 링크를 복사했습니다.');}catch{$('#share-url').select();toast('선택한 링크를 복사해주세요.');}};
$('#rail-add').onclick=()=>user?openProject():toast('로그인 후 프로젝트를 만들 수 있습니다.');$('#empty-create').onclick=()=>openProject();$('#project-settings').onclick=()=>openProject(true);$('#new-task').onclick=()=>newTask();$('#search').oninput=renderBoard;$('#status-filter').onchange=renderBoard;$('#owner-filter').onchange=renderBoard;
function changeView(next){view=next;for(const v of ['timeline','list']){$('#'+v+'-tab').classList.toggle('active',v===view);$('#'+v+'-tab').setAttribute('aria-selected',String(v===view));}renderBoard();}$('#timeline-tab').onclick=()=>changeView('timeline');$('#list-tab').onclick=()=>changeView('list');$('.view-tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();changeView(view==='timeline'?'list':'timeline');$('#'+view+'-tab').focus();}};
function moveMonth(n){month=addDays(month,n*30);renderBoard();}$('#prev-month').onclick=()=>moveMonth(-1);$('#next-month').onclick=()=>moveMonth(1);$('#today').onclick=()=>{const p=current(),t=today();month=p&&t<=p.start?p.start:addDays(t,-3);if(p&&month<p.start)month=p.start;changeView('timeline');const cell=$('.date-header [data-date="'+today()+'"]');if(cell){const content=$('#board-content');const left=parseInt(getComputedStyle($('.timeline')).getPropertyValue('--label'));content.scrollTo({left:Math.max(0,cell.getBoundingClientRect().left-content.getBoundingClientRect().left+content.scrollLeft-left-80),behavior:'smooth'});}};
$('#mobile-project').onchange=e=>switchProject(e.target.value);$('#mobile-add').onclick=()=>openProject();
$('#connect-github').onclick=()=>askName(); $('#github-form').onsubmit=e=>{e.preventDefault();const name=e.target.elements.name.value.trim();if(!name){$('#github-error').textContent='이름을 입력해주세요.';return;}store?.setName(name);displayAccount();$('#github-dialog').close();toast('이름을 저장했습니다. 기록에 이 이름이 남습니다.');const next=afterName;afterName=null;next?.();}; $('#github-dialog').addEventListener('close',()=>{$('#github-error').textContent='';}); $('#refresh').onclick=async()=>{await store?.refresh();};
window.addEventListener('offline',()=>connection('오프라인 · 저장 전 연결 필요'));window.addEventListener('online',()=>connection('연결 확인 중'));
if(demo){user={uid:'demo',email:'체험 사용자',canEdit:true};const data=demoData();projects=data.projects;selectedId='demo';tasks=data.tasks;month=data.projects[0].start;displayAccount();connection('샘플 체험');render();}else{displayAccount();try{const {createStore}=await import('./sheets-store.mjs');store=await createStore();store.watchAuth(next=>{unsubscribeTasks();store.stopProjects();user=next;projects=[];tasks=[];selectedId=null;$$('dialog[open]').filter(d=>d.id!=='github-dialog').forEach(d=>d.close());displayAccount();connection('데이터 불러오는 중');store.watchProjects(user,rows=>{projects=rows;if(pendingProjectId&&rows.some(p=>p.id===pendingProjectId)){switchProject(pendingProjectId);pendingProjectId=null;}if(!rows.some(p=>p.id===selectedId)){unsubscribeTasks();tasks=[];selectedId=null;const requested=new URLSearchParams(location.search).get('project');switchProject(rows.find(p=>p.id===requested)?.id||rows[0]?.id||null);}render();connection('공유 데이터 연결됨',true);},e=>{connection('데이터 연결 확인 필요');toast(errorMessage(e));if(!projects.length){$('#empty-projects').hidden=false;$('#empty-projects').innerHTML='<h2>데이터 연결을 확인해주세요</h2><p>'+esc(errorMessage(e))+'</p><button class="btn" id="retry-github">다시 연결</button>';$('#retry-github').onclick=()=>store.refresh();}});});}catch(e){connection('연결 실패');toast(errorMessage(e));}}

const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(modelContext.registerTool({name:'read_project_board',title:'프로젝트 현황 읽기',description:'현재 사용자가 볼 수 있는 선택된 프로젝트와 필터된 업무를 읽습니다. 저장하거나 수정하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('빈 객체를 전달해주세요.');if(!user)throw Error('로그인이 필요합니다.');return {demo,project:current()?.name??null,summary:summary(tasks),tasks:filtered().map(({title,owner,status,percent,start,end})=>({title,owner,status,percent,start,end}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
