import {githubConfig} from './github-config.mjs';
import {assertRevision,validateTask,validateProject,uid} from './model.mjs';
const emptyBoard=()=>({schemaVersion:1,revision:0,projects:[],tasks:{}});
const encode=text=>{const bytes=new TextEncoder().encode(text);let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary);};
const decode=text=>new TextDecoder().decode(Uint8Array.from(atob(text.replace(/\s/g,'')),c=>c.charCodeAt(0)));
export async function createStore({fetcher=globalThis.fetch,config=githubConfig,intervals=true}={}){
 let token='',user={uid:'guest',email:'조회 전용',canEdit:false},board=emptyBoard(),authCallback=()=>{},projectsCallback=null,projectsError=()=>{},timer=null,repoChecked=false,queue=Promise.resolve();
 const taskSubscribers=new Set(),base=`https://api.github.com/repos/${encodeURIComponent(config.owner)}/${encodeURIComponent(config.repo)}`,path=config.dataPath.split('/').map(encodeURIComponent).join('/');
 async function request(url,options={}){const res=await fetcher(url,{...options,cache:'no-store',headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(token?{Authorization:`Bearer ${token}`}:{ }),...options.headers}});return res;}
 async function fail(res){let message='GitHub 연결에 실패했습니다. 인터넷 연결을 확인해주세요.';if(res.status===401)message='GitHub 토큰을 확인해주세요. 만료되었다면 다시 연결해주세요.';else if(res.status===403||res.status===429)message=res.headers.get('x-ratelimit-remaining')==='0'?'GitHub 조회 한도에 도달했습니다. 잠시 후 새로고침하거나 편집 계정으로 연결해주세요.':'저장소 접근 권한이 없습니다. 토큰의 GA-HR 저장소와 Contents 읽기·쓰기 권한을 확인해주세요.';else if(res.status===404)message='저장소에 접근할 수 없습니다. 비공개 저장소라면 GitHub 연결이 필요합니다.';else if(res.status>=500)message='GitHub 서버가 응답하지 않습니다. 입력 내용은 유지되니 잠시 후 다시 저장해주세요.';throw Error(message);}
 async function read(){if(!repoChecked){const meta=await request(base);if(!meta.ok)await fail(meta);repoChecked=true;}const res=await request(`${base}/contents/${path}?ref=${encodeURIComponent(config.branch)}`);if(res.status===404)return {board:emptyBoard(),sha:null};if(!res.ok)await fail(res);const data=await res.json();if(data.encoding!=='base64'||!data.content)throw Error('프로젝트 데이터 파일이 올바르지 않거나 너무 큽니다. 관리자에게 확인해주세요.');const parsed=JSON.parse(decode(data.content));if(parsed.schemaVersion!==1||!Array.isArray(parsed.projects)||!parsed.tasks||typeof parsed.tasks!=='object')throw Error('지원하지 않는 프로젝트 데이터 형식입니다. 파일을 확인해주세요.');return {board:parsed,sha:data.sha};}
 function emit(){projectsCallback?.([...board.projects].sort((a,b)=>a.start.localeCompare(b.start)));for(const s of taskSubscribers)s.callback(board.tasks[s.pid]||[],false);}
 async function refresh(){try{const next=await read();if(next.board.revision>=board.revision){board=next.board;emit();}}catch(e){projectsError(e);}}
 function schedule(){clearInterval(timer);if(intervals)timer=setInterval(refresh,token?30000:120000);}
 function requireEditor(){if(!user.canEdit||!token)throw Error('편집 내용을 저장하려면 GitHub 계정을 연결해주세요.');return user;}
 function mutate(change,message){const run=async()=>{requireEditor();for(let attempt=0;attempt<3;attempt++){const latest=await read(),next=structuredClone(latest.board);change(next);next.revision=latest.board.revision+1;next.updatedAt=new Date().toISOString();next.updatedBy=user.email;const content=encode(JSON.stringify(next,null,2)+'\n');if(content.length>1200000)throw Error('프로젝트 데이터가 저장 한도에 가까워졌습니다. 관리자에게 데이터 분리를 요청해주세요.');let res;try{res=await request(`${base}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,content,branch:config.branch,...(latest.sha?{sha:latest.sha}:{})})});}catch{throw Error('저장 결과를 확인하지 못했습니다. 이 창의 입력을 복사한 뒤 새로고침하여 GitHub 반영 여부를 확인해주세요.');}if(res.status===409||res.status===422){if(attempt<2)continue;throw Error('다른 변경사항과 겹쳤습니다. 입력을 유지했으니 잠시 후 다시 저장해주세요.');}if(!res.ok)await fail(res);board=next;emit();return;} };const result=queue.then(run,run);queue=result.catch(()=>{});return result;}
 return {
  async login(value){const previous=token;token=value.trim();try{const res=await request('https://api.github.com/user');if(!res.ok)await fail(res);const profile=await res.json(),repo=await request(base);if(!repo.ok)await fail(repo);const details=await repo.json();if(!details.permissions?.push)throw Error('이 GitHub 계정에는 GA-HR 저장소 쓰기 권한이 없습니다. 저장소 소유자에게 협업자 등록을 요청해주세요.');repoChecked=true;user={uid:String(profile.id),email:profile.login,canEdit:true};authCallback(user);schedule();}catch(e){token=previous;throw e;}},
  async logout(){token='';user={uid:'guest',email:'조회 전용',canEdit:false};repoChecked=false;authCallback(user);schedule();},
  watchAuth(callback){authCallback=callback;queueMicrotask(()=>callback(user));return ()=>{authCallback=()=>{};};},
  stopProjects(){projectsCallback=null;clearInterval(timer);timer=null;},
  watchProjects(_user,callback,error){projectsCallback=callback;projectsError=error;refresh();schedule();},
  watchTasks(pid,callback,error){const s={pid,callback,error};taskSubscribers.add(s);queueMicrotask(()=>{if(taskSubscribers.has(s))callback(board.tasks[pid]||[],false);});return ()=>taskSubscribers.delete(s);},
  refresh,
  async saveProject(input){const editor=requireEditor(),data=validateProject(input),id=data.id||uid();await mutate(b=>{const at=b.projects.findIndex(p=>p.id===id);if(data.id){if(at<0)throw Error('프로젝트가 삭제되었습니다.');assertRevision(b.projects[at].version,data.version);if((b.tasks[id]||[]).some(t=>t.start<data.start||t.end>data.end))throw Error('업무가 새 프로젝트 기간을 벗어납니다. 업무 일정을 먼저 조정해주세요.');b.projects[at]={...b.projects[at],name:data.name,description:data.description,start:data.start,end:data.end,version:data.version+1};}else{b.projects.push({id,name:data.name,description:data.description,start:data.start,end:data.end,ownerUid:editor.uid,ownerLogin:editor.email,version:1});b.tasks[id]=[];}},`projects: ${data.id?'update':'create'} project`);return id;},
  async saveTask(pid,input){requireEditor();const data=validateTask(input),id=data.id||uid();await mutate(b=>{const p=b.projects.find(p=>p.id===pid);if(!p)throw Error('프로젝트가 삭제되었습니다.');if(data.start<p.start||data.end>p.end)throw Error('업무 일정은 프로젝트 기간 안에 설정해주세요.');const rows=b.tasks[pid]||[],at=rows.findIndex(t=>t.id===id);if(data.id){if(at<0)throw Error('다른 사람이 이 업무를 삭제했습니다.');assertRevision(rows[at].version,data.version);}const record={...data,id,version:data.id?data.version+1:1,updatedAt:new Date().toISOString(),updatedBy:user.email};if(at<0)rows.push(record);else rows[at]=record;b.tasks[pid]=rows;},`projects: ${data.id?'update':'create'} task`);return id;},
  async deleteTask(pid,task){await mutate(b=>{const rows=b.tasks[pid]||[],current=rows.find(t=>t.id===task.id);if(!current)return;assertRevision(current.version,task.version);b.tasks[pid]=rows.filter(t=>t.id!==task.id);},'projects: delete task');},
  destroy(){clearInterval(timer);taskSubscribers.clear();projectsCallback=null;authCallback=()=>{};token='';}
 };
}
