import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../github-store.mjs';
function server(){let board={schemaVersion:1,revision:0,projects:[],tasks:{}},sha='s0',version=0,forcedConflict=false;const writes=[];return {writes,get board(){return board;},forceConflict(){forcedConflict=true;},async fetcher(url,options={}){const headers=options.headers||{};if(url.endsWith('/user'))return Response.json({id:12,login:'editor'});if(!url.includes('/contents/'))return Response.json({permissions:{push:true}});if(options.method!=='PUT')return Response.json({sha,encoding:'base64',content:Buffer.from(JSON.stringify(board)).toString('base64')});if(!headers.Authorization)return new Response('',{status:401});const body=JSON.parse(options.body);if(forcedConflict){forcedConflict=false;sha='s'+(++version);return new Response('',{status:409});}if(body.sha!==sha)return new Response('',{status:409});board=JSON.parse(Buffer.from(body.content,'base64').toString('utf8'));sha='s'+(++version);writes.push(body);return Response.json({content:{sha}});}};}
const project={name:'테스트 프로젝트',description:'독립 보드',start:'2026-09-01',end:'2026-10-31'};
const task={id:null,title:'준비 업무',phase:'준비',owner:'',start:'2026-09-30',end:'2026-10-02',status:'doing',percent:40,blocker:'',link:'',checklist:[],logs:[],version:0};
async function editor(s){const store=await createStore({fetcher:s.fetcher,intervals:false});await store.login('test-token');return store;}
test('로그인하지 않은 방문자는 저장할 수 없다',async()=>{const s=server(),a=await createStore({fetcher:s.fetcher,intervals:false});await assert.rejects(a.saveProject(project),/GitHub/);assert.equal(s.writes.length,0);a.destroy();});
test('GitHub JSON에 한국어 프로젝트와 미지정 업무를 저장한다',async()=>{const s=server(),a=await editor(s),pid=await a.saveProject(project),tid=await a.saveTask(pid,task);assert.equal(s.board.projects[0].name,project.name);assert.equal(s.board.tasks[pid][0].owner,'');assert.equal(s.board.tasks[pid][0].id,tid);assert.equal(JSON.stringify(s.board).includes('test-token'),false);a.destroy();});
test('두 편집자가 같은 업무를 수정하면 이전 버전 저장을 거부한다',async()=>{const s=server(),a=await editor(s),b=await editor(s),pid=await a.saveProject(project);await a.saveTask(pid,task);const old=structuredClone(s.board.tasks[pid][0]);await a.saveTask(pid,{...old,title:'먼저 저장한 변경'});await assert.rejects(b.saveTask(pid,{...old,title:'오래된 변경'}),/다른 사람이/);assert.equal(s.board.tasks[pid][0].title,'먼저 저장한 변경');a.destroy();b.destroy();});
test('서로 다른 업무의 편집은 최신 JSON에 합쳐서 보존한다',async()=>{const s=server(),a=await editor(s),b=await editor(s),pid=await a.saveProject(project);await a.saveTask(pid,task);await a.saveTask(pid,{...task,title:'다른 업무'});const [one,two]=structuredClone(s.board.tasks[pid]);await a.saveTask(pid,{...one,title:'A 변경'});await b.saveTask(pid,{...two,title:'B 변경'});assert.deepEqual(s.board.tasks[pid].map(t=>t.title),['A 변경','B 변경']);a.destroy();b.destroy();});
test('저장소 SHA 충돌 시 최신 내용을 다시 읽고 재시도한다',async()=>{const s=server(),a=await editor(s);s.forceConflict();await a.saveProject(project);assert.equal(s.board.projects.length,1);assert.equal(s.writes.length,1);a.destroy();});
test('다른 사람이 수정한 업무는 오래된 버전으로 삭제할 수 없다',async()=>{const s=server(),a=await editor(s),pid=await a.saveProject(project);await a.saveTask(pid,task);const old=structuredClone(s.board.tasks[pid][0]);await a.saveTask(pid,{...old,percent:70});await assert.rejects(a.deleteTask(pid,old),/다른 사람이/);assert.equal(s.board.tasks[pid].length,1);a.destroy();});
test('프로젝트 기간 축소가 기존 업무를 제외하면 거부한다',async()=>{const s=server(),a=await editor(s),pid=await a.saveProject(project);await a.saveTask(pid,task);await assert.rejects(a.saveProject({...s.board.projects[0],end:'2026-09-20'}),/벗어납니다/);a.destroy();});
