import {STATUSES,uid,today,addDays,dayRange,daysBetween,summary,validateTask,validateProject,normalizeEmails,safeUrl,demoData} from './model.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let demo=new URLSearchParams(location.search).has('demo'),user=null,store=null,projects=[],tasks=[],selectedId=null,unsubscribeTasks=()=>{},editing=null,editingProject=null,draftChecks=[],view='timeline',month=today().slice(0,7),toastTimer,loading=false,shareVersion=null;
const demoTasks=new Map();
let pendingProjectId=null;
const canEdit=()=>demo||!!user?.canEdit;
const current=()=>projects.find(p=>p.id===selectedId);
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
function connection(text,live=false){$('#connection').textContent=text;$('#connection').classList.toggle('live',live);}
function errorMessage(error){if(error.code==='unavailable')return '연결이 끊어졌습니다. 입력 내용을 유지했으니 연결 후 다시 저장해주세요.';if(error.code?.startsWith('auth/'))return error.code==='auth/too-many-requests'?'로그인 시도가 많습니다. 잠시 후 다시 시도해주세요.':'로그인에 실패했습니다. 이메일과 비밀번호, 네트워크 연결을 확인해주세요.';return error.message||'작업을 처리하지 못했습니다. 다시 시도해주세요.';}
async function busy(form,work){const controls=[...form.querySelectorAll('button')];controls.forEach(b=>b.disabled=true);try{await work();}finally{controls.forEach(b=>b.disabled=false);}}
const hasName=()=>demo||!!user?.named;let afterName=null;function askName(then=null){afterName=then;const f=$('#github-form');f.elements.name.value=user?.named?user.email:'';$('#github-error').textContent='';$('#github-dialog').showModal();}
function displayAccount(){const name=demo?'샘플 체험':user?.named?user.email:'이름 미설정';$('#account-name').textContent=name;$('#avatar').textContent=name.slice(0,1).toUpperCase();$('#demo-banner').hidden=!demo;$('#workspace').hidden=false;$('#connect-github').hidden=demo;$('#connect-github').textContent=hasName()?'이름 변경':'내 이름 설정';$('#refresh').hidden=demo;}

function switchProject(id){if(selectedId===id)return;if(demo&&selectedId)demoTasks.set(selectedId,tasks);selectedId=id;tasks=demo?(demoTasks.get(id)||[]):[];unsubscribeTasks();const p=current();if(p){const t=today();month=(t>=p.start&&t<=p.end?t:p.start).slice(0,7);if(!demo){loading=true;unsubscribeTasks=store.watchTasks(id,(rows,cached)=>{tasks=rows;loading=false;connection(cached?'연결 확인 중':'공유 데이터 연결됨',!cached);render();if(editing&&$('#task-dialog').open){const latest=tasks.find(t=>t.id===editing.id);$('#conflict-note').hidden=!!latest&&latest.version===editing.version;}},e=>{loading=false;tasks=[];connection('공유 데이터 확인 필요');render();$('#board-content').innerHTML=`<div class="empty-result">${esc(errorMessage(e))}</div>`;});}}const url=new URL(location.href);if(id)url.searchParams.set('project',id);else url.searchParams.delete('project');history.replaceState(null,'',url);render();}
function render(){const p=current();$('#project-list').innerHTML=projects.map(p=>`<button class="project-nav ${p.id===selectedId?'active':''}" data-project="${esc(p.id)}">${esc(p.name)}</button>`).join('');$('#empty-projects').hidden=!!p;$('.project-heading').hidden=!p;$('.metrics').hidden=!p;$('.board').hidden=!p;$('#attention').hidden=!p;if(!p)return;$('#project-title').textContent=p.name;$('#project-desc').textContent=p.description;$('#project-period').textContent=`${p.start.replaceAll('-','.')} — ${p.end.replaceAll('-','.')}`;$('#member-count').textContent='링크로 함께 관리';$('#project-settings').disabled=!canEdit();$('#new-task').disabled=!canEdit();const sum=summary(tasks);$('#stat-percent').innerHTML=`${sum.percent}<em>%</em>`;$('#overall-progress').style.width=sum.percent+'%';$('#stat-done').innerHTML=`${sum.done} <em>/ ${sum.total}</em>`;$('#stat-late').textContent=sum.late;$('#stat-unassigned').textContent=sum.unassigned;$('#mobile-project').innerHTML=projects.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');$('#mobile-project').value=p.id;const prev=$('#owner-filter').value;const owners=[...new Set(tasks.map(t=>t.owner).filter(Boolean))].sort();$('#owner-filter').innerHTML='<option value="all">모든 담당자</option><option value="unassigned">미지정</option>'+owners.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('');$('#owner-filter').value=[...$('#owner-filter').options].some(o=>o.value===prev)?prev:'all';$('#owners').innerHTML=owners.map(o=>`<option>${esc(o)}</option>`).join('');renderBoard();$('#attention').innerHTML=(sum.blocked?`<button class="attention-item" data-attention="blocked"><span>⚑</span><span><b>도움이 필요한 업무 ${sum.blocked}건</b> · 막힌 이유를 확인하고 함께 해결해주세요.</span></button>`:'')+(sum.unassigned?`<button class="attention-item" data-attention="unassigned"><span>◎</span><span><b>담당자 미지정 ${sum.unassigned}건</b> · 업무를 맡을 사람을 정해주세요.</span></button>`:'');}
function filtered(){const search=$('#search').value.toLowerCase(),status=$('#status-filter').value,owner=$('#owner-filter').value;return tasks.filter(t=>(t.title+' '+t.phase+' '+t.owner).toLowerCase().includes(search)&&(status==='all'||(status==='late'?t.end<today()&&t.status!=='done':t.status===status))&&(owner==='all'||(owner==='unassigned'?!t.owner:t.owner===owner))).sort((a,b)=>a.start.localeCompare(b.start)||a.title.localeCompare(b.title));}
function renderBoard(){const rows=filtered(),p=current();if(!p)return;$('#month-label').textContent=month.replace('-','년 ')+'월';$('#task-count').textContent=`업무 ${rows.length}개 / 전체 ${tasks.length}개`;
if(loading){$('#board-content').innerHTML='<div class="empty-result">업무를 불러오고 있습니다…</div>';return;}if(!rows.length){$('#board-content').innerHTML=`<div class="empty-result">${tasks.length?'조건에 맞는 업무가 없습니다. 필터를 변경해보세요.':'아직 등록된 업무가 없습니다. 첫 업무를 추가해보세요.'}<br><button class="btn primary" style="margin-top:16px" data-new-task>＋ 업무 추가</button></div>`;return;}
if(view==='list'){$('#board-content').innerHTML=`<table class="list-table"><thead><tr><th>업무</th><th>담당자</th><th>상태</th><th>일정</th><th>진행률</th><th>준비사항</th></tr></thead><tbody>${rows.map(t=>`<tr data-task="${esc(t.id)}"><td><button class="btn ghost" data-task="${esc(t.id)}">${esc(t.title)}</button></td><td>${esc(t.owner||'미지정')}</td><td><span class="badge ${esc(t.status)}">${STATUSES[t.status]}</span></td><td class="${t.end<today()&&t.status!=='done'?'late-text':''}">${t.start.slice(5)} ~ ${t.end.slice(5)}</td><td>${t.percent}%</td><td>${t.checklist.filter(c=>c.done).length}/${t.checklist.length}</td></tr>`).join('')}</tbody></table>`;return;}
const first=month===today().slice(0,7)?addDays(today(),-7):month+'-01',last=addDays(first,34),days=dayRange(first,last),week=['일','월','화','수','목','금','토'];
$('#month-label').textContent=first.slice(0,4)+'년 '+Number(first.slice(5,7))+'월'+(first.slice(0,7)!==last.slice(0,7)?' – '+Number(last.slice(5,7))+'월':'');
const dayClass=d=>`${[0,6].includes(new Date(d).getUTCDay())?'weekend':''} ${d===today()?'today':''}`;
let html=`<div class="timeline"><div class="timeline-row date-header"><div class="row-label"><span>업무 / 준비사항</span><span>담당자</span></div><div class="days">${days.map(d=>`<div class="day-cell ${dayClass(d)}" data-date="${d}"><span>${week[new Date(d).getUTCDay()]}</span><b>${d.endsWith('-01')?Number(d.slice(5,7))+'/1':Number(d.slice(-2))}</b></div>`).join('')}</div></div>`;
const phases=[...new Set(rows.map(t=>t.phase||'일반'))];for(const phase of phases){const group=rows.filter(t=>(t.phase||'일반')===phase);html+=`<div class="timeline-row group-row"><div class="row-label">${esc(phase)} <span class="group-count">${group.length}</span></div><div class="group-fill"></div></div>`;for(const t of group){const begin=t.start<first?first:t.start,finish=t.end>last?last:t.end,visible=begin<=last&&finish>=first;const label=`${t.title} · ${STATUSES[t.status]} · ${t.percent}%`;html+=`<div class="timeline-row"><button class="row-label" data-task="${esc(t.id)}"><span class="status-icon ${esc(t.status)}">${t.status==='done'?'✓':t.status==='blocked'?'!':''}</span><span class="task-text"><span class="task-name">${esc(t.title)}</span><span class="task-sub"><span>☑ ${t.checklist.filter(c=>c.done).length}/${t.checklist.length}</span><span class="${t.end<today()&&t.status!=='done'?'late-text':''}">${t.end<today()&&t.status!=='done'?'지연 · ':''}${STATUSES[t.status]}</span></span></span><span class="owner-pill ${!t.owner?'unassigned':''}">${esc(t.owner||'미지정')}</span></button><div class="days">${days.map(d=>`<button class="day-cell ${dayClass(d)} ${t.logs.some(l=>l.date===d)?'has-log':''}" data-task="${esc(t.id)}" data-log-date="${d}" aria-label="${esc(t.title)} ${d} 추진 기록"></button>`).join('')}${visible?`<button class="bar ${esc(t.status)}" style="left:calc(${daysBetween(first,begin)} * var(--day) + 4px);width:calc(${daysBetween(begin,finish)+1} * var(--day) - 8px)" data-task="${esc(t.id)}" title="${esc(label)}" aria-label="${esc(label)}"><i class="bar-fill" style="width:${t.percent}%"></i><span>${esc(t.owner||STATUSES[t.status])}</span><b>${t.percent}%</b></button>`:''}</div></div>`;}}$('#board-content').innerHTML=html+'</div>';}
function newTask(date=today()){if(!canEdit())return;if(!hasName()){askName(()=>newTask(date));return;}const p=current();if(!p)return;openTask({id:null,title:'',phase:'준비',owner:'',start:date<p.start?p.start:date>p.end?p.end:date,end:date<p.start?p.start:date>p.end?p.end:date,status:'todo',percent:0,blocker:'',link:'',checklist:[],logs:[],version:0},date);}
function openTask(task,date=today()){editing=structuredClone(task);draftChecks=structuredClone(task.checklist);const form=$('#task-form');form.reset();for(const key of ['title','phase','owner','start','end','status','percent','blocker','link'])form.elements.namedItem(key).value=task[key]??'';form.elements.logDate.value=date;$('#task-mode').textContent=task.id?'업무 상세':'새로운 업무';$('#task-dialog-title').textContent=task.id?'업무 수정':'업무 추가';$('#task-error').textContent='';$('#conflict-note').hidden=true;$('#delete-task').hidden=!task.id;renderChecks();renderStatus();$('#task-history').innerHTML=[...task.logs].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)).map(l=>`<article class="history-entry"><div class="history-meta"><b>${esc(l.date)}</b><span>${esc(l.author)}</span></div><p>${esc(l.note)}</p><div class="history-state">${STATUSES[l.status]} · ${l.percent}%</div></article>`).join('')||'<p class="helper">아직 등록된 추진 기록이 없습니다.</p>';for(const field of form.querySelectorAll('input,textarea,select,button:not([data-close])'))field.disabled=!canEdit();form.querySelector('[type=submit]').hidden=!canEdit();$('#delete-task').hidden=!canEdit()||!task.id;if(canEdit())renderStatus();$('#task-dialog-title').textContent=canEdit()?(task.id?'업무 수정':'업무 추가'):'업무 상세';$('#task-dialog').showModal();$('#task-form .dialog-body').scrollTop=0;}
function renderChecks(){$('#checklist').innerHTML=draftChecks.map(c=>`<div class="check-row"><label><input type="checkbox" data-check="${esc(c.id)}" ${c.done?'checked':''}>${esc(c.text)}</label><button type="button" class="icon-btn" data-remove-check="${esc(c.id)}" aria-label="${esc(c.text)} 삭제">×</button></div>`).join('');$('#check-count').textContent=`${draftChecks.filter(c=>c.done).length} / ${draftChecks.length}`;}
function renderStatus(){const f=$('#task-form'),done=f.elements.status.value==='done';if(done)f.elements.percent.value=100;else if(+f.elements.percent.value===100)f.elements.percent.value=95;f.elements.percent.disabled=done;$('#percent-label').textContent=f.elements.percent.value+'%';$('#blocker-label').hidden=f.elements.status.value!=='blocked';f.elements.blocker.required=f.elements.status.value==='blocked';}
function openProject(existing=false){if(!canEdit())return;if(!hasName()){askName(()=>openProject(existing));return;}editingProject=existing?structuredClone(current()):null;const f=$('#project-form');f.reset();f.elements.name.value=editingProject?.name??'';f.elements.description.value=editingProject?.description??'';f.elements.start.value=editingProject?.start??today();f.elements.end.value=editingProject?.end??addDays(today(),30);$('#project-dialog-title').textContent=existing?'프로젝트 설정':'새 프로젝트';$('#project-error').textContent='';$('#project-dialog').showModal();}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){close.closest('dialog').close();return;}const project=e.target.closest('[data-project]');if(project){switchProject(project.dataset.project);return;}const task=e.target.closest('[data-task]');if(task){const record=tasks.find(t=>t.id===task.dataset.task);if(record)openTask(record,task.dataset.logDate||today());return;}if(e.target.closest('[data-new-task]'))newTask();const del=e.target.closest('[data-remove-check]');if(del){draftChecks=draftChecks.filter(c=>c.id!==del.dataset.removeCheck);renderChecks();}const metric=e.target.closest('[data-metric],[data-attention]');if(metric){const value=metric.dataset.metric||metric.dataset.attention;$('#status-filter').value=['done','late','blocked'].includes(value)?value:'all';$('#owner-filter').value=value==='unassigned'?'unassigned':'all';renderBoard();}});
$('#checklist').addEventListener('change',e=>{const c=draftChecks.find(c=>c.id===e.target.dataset.check);if(c)c.done=e.target.checked;renderChecks();});
$('#add-check').onclick=()=>{const input=$('#check-input'),text=input.value.trim();if(!text)return;if(draftChecks.length>=50){toast('준비사항은 최대 50개까지 등록할 수 있습니다.');return;}draftChecks.push({id:uid(),text,done:false});input.value='';renderChecks();input.focus();};$('#check-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#add-check').click();}};
$('#task-form').elements.status.onchange=renderStatus;$('#task-form').elements.percent.oninput=()=>{$('#percent-label').textContent=$('#task-form').elements.percent.value+'%';};
$('#task-form').onsubmit=async e=>{e.preventDefault();if(!hasName()){askName();return;}const form=e.target;$('#task-error').textContent='';await busy(form,async()=>{try{const data=Object.fromEntries(new FormData(form)),p=current();let record=validateTask({...editing,...data,percent:Number(form.elements.percent.value),checklist:draftChecks,logs:[...editing.logs]});if(record.start<p.start||record.end>p.end)throw Error('업무 일정은 프로젝트 시작일과 종료일 안에 설정해주세요.');if(data.note.trim()){record.logs.push({id:uid(),date:data.logDate,note:data.note.trim(),status:record.status,percent:record.percent,author:user.email,createdAt:new Date().toISOString()});}else if(editing.id&&(editing.status!==record.status||editing.percent!==record.percent)){record.logs.push({id:uid(),date:today(),note:`상태 변경: ${STATUSES[record.status]} (${record.percent}%)`,status:record.status,percent:record.percent,author:user.email,createdAt:new Date().toISOString()});}delete record.note;delete record.logDate;record=validateTask(record);if(demo){record.id=record.id||uid();record.version++;const at=tasks.findIndex(t=>t.id===record.id);if(at<0)tasks.push(record);else tasks[at]=record;render();}else await store.saveTask(selectedId,record);$('#task-dialog').close();toast(demo?'샘플에 반영했습니다.':'변경사항을 저장했습니다.');}catch(err){$('#task-error').textContent=errorMessage(err);}});};
$('#delete-task').onclick=()=>$('#confirm-dialog').showModal();$('#confirm-dialog').addEventListener('close',async()=>{if($('#confirm-dialog').returnValue!=='delete')return;await busy($('#task-form'),async()=>{try{if(demo){tasks=tasks.filter(t=>t.id!==editing.id);render();}else await store.deleteTask(selectedId,editing);$('#task-dialog').close();toast('업무를 삭제했습니다.');}catch(e){$('#task-error').textContent=errorMessage(e);}});});
$('#project-form').onsubmit=async e=>{e.preventDefault();const f=e.target;$('#project-error').textContent='';await busy(f,async()=>{try{const data=validateProject({...editingProject,...Object.fromEntries(new FormData(f))});if(editingProject&&tasks.some(t=>t.start<data.start||t.end>data.end))throw Error('기존 업무가 새 프로젝트 기간을 벗어납니다. 업무 일정을 먼저 조정해주세요.');if(demo){if(editingProject){Object.assign(current(),data,{version:current().version+1});render();}else{data.id=uid();Object.assign(data,{ownerUid:user.uid,ownerEmail:user.email,memberEmails:[user.email],version:1});projects.push(data);switchProject(data.id);}}else{const id=await store.saveProject(data);if(!editingProject){pendingProjectId=id;if(projects.some(p=>p.id===id)){switchProject(id);pendingProjectId=null;}toast('프로젝트를 만들었습니다.');}}$('#project-dialog').close();}catch(err){$('#project-error').textContent=errorMessage(err);}});};
$('#share').onclick=()=>{$('#share-url').value=location.href;$('#share-dialog').showModal();};
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('#share-url').value);toast('프로젝트 링크를 복사했습니다.');}catch{$('#share-url').select();toast('선택한 링크를 복사해주세요.');}};
$('#rail-add').onclick=()=>user?openProject():toast('로그인 후 프로젝트를 만들 수 있습니다.');$('#empty-create').onclick=()=>openProject();$('#project-settings').onclick=()=>openProject(true);$('#new-task').onclick=()=>newTask();$('#search').oninput=renderBoard;$('#status-filter').onchange=renderBoard;$('#owner-filter').onchange=renderBoard;
function changeView(next){view=next;for(const v of ['timeline','list']){$('#'+v+'-tab').classList.toggle('active',v===view);$('#'+v+'-tab').setAttribute('aria-selected',String(v===view));}renderBoard();}$('#timeline-tab').onclick=()=>changeView('timeline');$('#list-tab').onclick=()=>changeView('list');$('.view-tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();changeView(view==='timeline'?'list':'timeline');$('#'+view+'-tab').focus();}};
function moveMonth(n){const date=new Date(month+'-01T00:00:00Z');date.setUTCMonth(date.getUTCMonth()+n);month=date.toISOString().slice(0,7);renderBoard();}$('#prev-month').onclick=()=>moveMonth(-1);$('#next-month').onclick=()=>moveMonth(1);$('#today').onclick=()=>{month=today().slice(0,7);changeView('timeline');const cell=$('.date-header [data-date="'+today()+'"]');if(cell){const content=$('#board-content');const left=parseInt(getComputedStyle($('.timeline')).getPropertyValue('--label'));content.scrollTo({left:Math.max(0,cell.getBoundingClientRect().left-content.getBoundingClientRect().left+content.scrollLeft-left-80),behavior:'smooth'});}};
$('#mobile-project').onchange=e=>switchProject(e.target.value);$('#mobile-add').onclick=()=>openProject();
$('#connect-github').onclick=()=>askName(); $('#github-form').onsubmit=e=>{e.preventDefault();const name=e.target.elements.name.value.trim();if(!name){$('#github-error').textContent='이름을 입력해주세요.';return;}store?.setName(name);displayAccount();$('#github-dialog').close();toast('이름을 저장했습니다. 기록에 이 이름이 남습니다.');const next=afterName;afterName=null;next?.();}; $('#github-dialog').addEventListener('close',()=>{$('#github-error').textContent='';}); $('#refresh').onclick=async()=>{await store?.refresh();};
window.addEventListener('offline',()=>connection('오프라인 · 저장 전 연결 필요'));window.addEventListener('online',()=>connection('연결 확인 중'));
if(demo){user={uid:'demo',email:'체험 사용자',canEdit:true};const data=demoData();projects=data.projects;selectedId='demo';tasks=data.tasks;displayAccount();connection('샘플 체험');render();}else{displayAccount();try{const {createStore}=await import('./sheets-store.mjs');store=await createStore();store.watchAuth(next=>{unsubscribeTasks();store.stopProjects();user=next;projects=[];tasks=[];selectedId=null;$$('dialog[open]').filter(d=>d.id!=='github-dialog').forEach(d=>d.close());displayAccount();connection('데이터 불러오는 중');store.watchProjects(user,rows=>{projects=rows;if(pendingProjectId&&rows.some(p=>p.id===pendingProjectId)){switchProject(pendingProjectId);pendingProjectId=null;}if(!rows.some(p=>p.id===selectedId)){unsubscribeTasks();tasks=[];selectedId=null;const requested=new URLSearchParams(location.search).get('project');switchProject(rows.find(p=>p.id===requested)?.id||rows[0]?.id||null);}render();connection('공유 데이터 연결됨',true);},e=>{connection('데이터 연결 확인 필요');toast(errorMessage(e));if(!projects.length){$('#empty-projects').hidden=false;$('#empty-projects').innerHTML='<h2>데이터 연결을 확인해주세요</h2><p>'+esc(errorMessage(e))+'</p><button class="btn" id="retry-github">다시 연결</button>';$('#retry-github').onclick=()=>store.refresh();}});});}catch(e){connection('연결 실패');toast(errorMessage(e));}}

const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(modelContext.registerTool({name:'read_project_board',title:'프로젝트 현황 읽기',description:'현재 사용자가 볼 수 있는 선택된 프로젝트와 필터된 업무를 읽습니다. 저장하거나 수정하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('빈 객체를 전달해주세요.');if(!user)throw Error('로그인이 필요합니다.');return {demo,project:current()?.name??null,summary:summary(tasks),tasks:filtered().map(({title,owner,status,percent,start,end})=>({title,owner,status,percent,start,end}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
